# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\ProyectoFinal\login.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(308, 448)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(10, 10, 290, 410))
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(-20, 0, 331, 431))
        self.label.setStyleSheet("background-color:rgb(215, 193, 118\n"
");\n"
"border-radius:10px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.lineEditUsuario = QtWidgets.QLineEdit(self.widget)
        self.lineEditUsuario.setGeometry(QtCore.QRect(20, 210, 250, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEditUsuario.setFont(font)
        self.lineEditUsuario.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:1px solid rgba(0,0,0,0);\n"
"border-bottom-color:rgba(46,82,101,255);\n"
"color:rgb(255,255,255);\n"
"padding-bottom:7px")
        self.lineEditUsuario.setObjectName("lineEditUsuario")
        self.lineEditContra = QtWidgets.QLineEdit(self.widget)
        self.lineEditContra.setGeometry(QtCore.QRect(20, 260, 250, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEditContra.setFont(font)
        self.lineEditContra.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:1px solid rgba(0,0,0,0);\n"
"border-bottom-color:rgba(46,82,101,255);\n"
"color:rgb(255,255,255);\n"
"padding-bottom:7px")
        self.lineEditContra.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEditContra.setObjectName("lineEditContra")
        self.BtnIngresar = QtWidgets.QPushButton(self.widget)
        self.BtnIngresar.setGeometry(QtCore.QRect(20, 320, 250, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.BtnIngresar.setFont(font)
        self.BtnIngresar.setStyleSheet("QPushButton#pushButton{\n"
"background-color:rgb(70, 60, 29\n"
");\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px}\n"
"\n"
"QPushButton#pushButton:pressed{\n"
"padding-left:5px;\n"
"padding-right:5px;\n"
"background-color:rgb(127, 115, 77\n"
");\n"
"baackground-position:calc(100%-10px)center;\n"
"}\n"
"QPushButton#pushButton:hover{\n"
"background-color:rgb(153, 144, 113\n"
");\n"
"}\n"
"")
        self.BtnIngresar.setObjectName("BtnIngresar")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(66, 42, 161, 151))
        self.label_2.setText("")
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setPixmap(QtGui.QPixmap("d:\\ProyectoFinal\\../../Imágenes/logopupa.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Ingreso"))
        self.lineEditUsuario.setPlaceholderText(_translate("Form", "Usuario"))
        self.lineEditContra.setPlaceholderText(_translate("Form", "Contraseña"))
        self.BtnIngresar.setText(_translate("Form", "Ingresar"))
